favicon: /favicon.ico


# Nav Menus
menu:
    Index: /
    Archives: /archives
    Booklist: /booklist
    Resume: /resume

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/dingxianye']
    # - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['Dinghui.Ye Online', 'JavaWeb, BigData, Algorithm', 'http://dinghuiye.online/']
    - ['Derek重名了', '想开家面馆，可惜只会吃不会做，怎么办？在线等...', 'https://www.jianshu.com/u/cd2ecc3a1eb7']

# About
about_info:
    name: "Derek"
    bio: "王になる人"
    avatar: "/images/icon.png"

# Comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# Analytics
google_analytics: false
tencent_analytics: false
 
# Copyright Infomation
startyear: 2018
